ENVIRONMENT = "test"

#[db]
#host = "l8yc5u.stackhero-network.com"
#port = "5432"
#database = "test"
#username = "admin"
#password = "V7Bqqlbzx6zX9VAmcC0355dzZVNHdiYa"


[db]
host = "localhost"
port = "5432"
database = "test"
username = "postgres"
password = "postgres"


[cache_redis]
url = "redis://:9jm85p9z1m28zf8v34jr8x7dgpw5hgar6pacs4trfbfe3rk78t2t@professional-owl-c222061bfc.redisgreen.net:11042"

[celery_redis]
url = "rediss://default:eb1101f635b44826807ba6992778829d@us1-right-muskox-39790.upstash.io:39790"
