ENVIRONMENT = "production"

[angelone_broker]
id = "uuid"
username = "username"
password = "password"
api_key = "api_key"
totp = "totp_key"


[db]
host = "host"
port = "port"
database = "trading"
username = "user"
password = "password"


[trades_and_option_chain_redis]
url = "redis://:password@host:port"

strategy_id_uuid_namespace = "company_uuid"
