ENVIRONMENT = "production"

[db]
host = "l8yc5u.stackhero-network.com"
port = "5432"
database = "trading"
username = "admin"
password = "V7Bqqlbzx6zX9VAmcC0355dzZVNHdiYa"


[celery_redis]
url = "rediss://default:b58c9fd58a274c08a1eef6bfcc0a1a7f@us1-complete-halibut-37733.upstash.io:37733"


[cache_redis]
url = "redis://:9jm85p9z1m28zf8v34jr8x7dgpw5hgar6pacs4trfbfe3rk78t2t@professional-owl-c222061bfc.redisgreen.net:11042"
