ENVIRONMENT = "test"

[db]
host = "localhost"
port = "5432"
database = "test"
username = "postgres"
password = "postgres"

[celery_redis]
url = "rediss://default:eb1101f635b44826807ba6992778829d@us1-right-muskox-39790.upstash.io:39790"


[cache_redis]
host = "redis-16366.c8.us-east-1-4.ec2.cloud.redislabs.com"
port = "16366"
password = "ndzSBdflQ29c6nHcSRIejVTLtcffdjsb"
db = "test-redis"
