ENVIRONMENT = "test"

[db]
host = "localhost"
port = "5432"
database = "test"
username = "postgres"
password = "postgres"


[trades_and_option_chain_redis]
host = "redis-16366.c8.us-east-1-4.ec2.cloud.redislabs.com"
port = "16366"
password = "ndzSBdflQ29c6nHcSRIejVTLtcffdjsb"
db = "test-redis"
