ENVIRONMENT = "test"

[angelone_broker]
id = "uuid"
username = "username"
password = "password"
api_key = "api_key"
totp = "totp_key"


[db]
host = "localhost"
port = "5432"
database = "test"
username = "postgres"
password = "postgres"


[trades_and_option_chain_redis]
url="rediss://default:pass@host:port"
host = "test-redis-maheshkokare100.h.aivencloud.com"
port = "19849"
password = "AVNS_r8QLpaeqMeB3bM8cKGv"
db = "0"
