ENVIRONMENT = "test"

[angelone_broker]
id = "a02d2158-cf03-4527-b8a4-d4f4dee66e6d"
username = "M57484244"
password = "4286"
api_key = "rUhNkLeD"
totp = "KOZTYAU6NMG7RMZAEZOYIPYJZE"


[db]
host = "localhost"
port = "5432"
database = "test"
username = "postgres"
password = "postgres"


[trades_and_option_chain_redis]
host = "redis-12100.c233.eu-west-1-1.ec2.cloud.redislabs.com"
port = "12100"
password = "UmzKGgUzZkE4NMqjuzisvSUXSrLxGI6K"
db = "test"
