ENVIRONMENT = "test"

[db]
host = "localhost"
port = "5432"
database = "test"
username = "postgres"
password = "postgres"


[trades_and_option_chain_redis]
host = "redis-17407.c226.eu-west-1-3.ec2.cloud.redislabs.com"
port = "17407"
password = "7zzFkCNokCTtsdexYrmQH8Zu167UiO7E"
db = "test-redis"
