"""daily_profit updated

Revision ID: dcb9ea13b15a
Revises: 8967acf94e32
Create Date: 2024-02-11 03:50:11.585266

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "dcb9ea13b15a"
down_revision = "8967acf94e32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("daily_profit", sa.Column("todays_profit", sa.Float(), nullable=False))
    op.add_column("daily_profit", sa.Column("total_profit", sa.Float(), nullable=False))
    op.add_column("daily_profit", sa.Column("todays_future_profit", sa.Float(), nullable=False))
    op.add_column("daily_profit", sa.Column("total_future_profit", sa.Float(), nullable=False))
    op.drop_column("daily_profit", "future_profit")
    op.drop_column("daily_profit", "profit")
    op.add_column("strategy", sa.Column("future_funds", sa.Float(), nullable=True))
    op.alter_column(
        "strategy", "funds", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "strategy", "funds", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.drop_column("strategy", "future_funds")

    op.add_column(
        "daily_profit",
        sa.Column(
            "profit", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "daily_profit",
        sa.Column(
            "future_profit",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("daily_profit", "total_future_profit")
    op.drop_column("daily_profit", "todays_future_profit")
    op.drop_column("daily_profit", "total_profit")
    op.drop_column("daily_profit", "todays_profit")

    # ### end Alembic commands ###
