"""second_migration

Revision ID: bcf56a4ebb95
Revises: 84d3bebb3935
Create Date: 2023-06-05 00:51:10.766709

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bcf56a4ebb95"
down_revision = "84d3bebb3935"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_profit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profit", sa.Float(), nullable=False),
        sa.Column("future_profit", sa.Float(), nullable=False),
        sa.Column("strategy_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_profit_strategy_id"), "daily_profit", ["strategy_id"], unique=False
    )
    op.drop_index("ix_daily_profits_strategy_id", table_name="daily_profits")
    op.drop_table("daily_profits")
    op.add_column("take_away_profit", sa.Column("future_profit", sa.Float(), nullable=True))
    op.drop_column("take_away_profit", "futures_profit")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "take_away_profit",
        sa.Column(
            "futures_profit",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("take_away_profit", "future_profit")
    op.create_table(
        "daily_profits",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "profit", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("strategy_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategy.id"], name="daily_profits_strategy_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="daily_profits_pkey"),
    )
    op.create_index(
        "ix_daily_profits_strategy_id", "daily_profits", ["strategy_id"], unique=False
    )
    op.drop_index(op.f("ix_daily_profit_strategy_id"), table_name="daily_profit")
    op.drop_table("daily_profit")
    # ### end Alembic commands ###
