"""exit_received_at and entry_received_at_columns

Revision ID: fd1c782daaf3
Revises: bcf56a4ebb95
Create Date: 2023-06-12 20:52:58.130190

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "fd1c782daaf3"
down_revision = "bcf56a4ebb95"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("strategy", sa.Column("position", sa.String(), nullable=True))
    op.add_column("trade", sa.Column("future_entry_price_received", sa.Float(), nullable=True))
    op.add_column(
        "trade",
        sa.Column("entry_received_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "trade", sa.Column("entry_at", postgresql.TIMESTAMP(timezone=True), nullable=False)
    )
    op.add_column(
        "trade", sa.Column("exit_received_at", postgresql.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "trade", sa.Column("exit_at", postgresql.TIMESTAMP(timezone=True), nullable=True)
    )
    op.drop_index("ix_trade_action", table_name="trade")
    op.drop_column("trade", "future_received_entry_price")
    op.drop_column("trade", "placed_at")
    op.drop_column("trade", "action")
    op.drop_column("trade", "exited_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade",
        sa.Column(
            "exited_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column("trade", sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column(
        "trade",
        sa.Column(
            "placed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "trade",
        sa.Column(
            "future_received_entry_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index("ix_trade_action", "trade", ["action"], unique=False)
    op.drop_column("trade", "exit_at")
    op.drop_column("trade", "exit_received_at")
    op.drop_column("trade", "entry_at")
    op.drop_column("trade", "entry_received_at")
    op.drop_column("trade", "future_entry_price_received")
    op.drop_column("strategy", "position")
    # ### end Alembic commands ###
