"""added twoFA and few columns mandatory

Revision ID: b41d3a33634e
Revises: fd1c782daaf3
Create Date: 2023-07-01 17:32:33.779988

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b41d3a33634e"
down_revision = "fd1c782daaf3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("broker_clients", sa.Column("twoFA", sa.Integer(), nullable=False))
    op.alter_column("broker_clients", "api_key", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("broker_clients", "app_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("broker_clients", "totp", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("broker_clients", "totp", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("broker_clients", "app_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("broker_clients", "api_key", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("broker_clients", "twoFA")
    # ### end Alembic commands ###
