"""added compounding and contracts column to cfd_strategy

Revision ID: 6b6a63fdbea5
Revises: 2d391b35abe8
Create Date: 2023-12-22 11:26:09.742310

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6b6a63fdbea5"
down_revision = "2d391b35abe8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cfd_strategy",
        sa.Column("compounding", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column("cfd_strategy", sa.Column("contracts", sa.Float(), nullable=True))
    op.add_column(
        "cfd_strategy",
        sa.Column(
            "funds_usage_percent", sa.Float(), nullable=False, server_default=sa.text("1.0")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cfd_strategy", "contracts")
    op.drop_column("cfd_strategy", "compounding")
    op.drop_column("cfd_strategy", "funds_usage_percent")
    # ### end Alembic commands ###
