"""action in trade and margin min quntity compounding cols in strategy

Revision ID: aa5951fdf5de
Revises: 6b6a63fdbea5
Create Date: 2024-01-16 14:30:22.490608

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "aa5951fdf5de"
down_revision = "6b6a63fdbea5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("strategy", sa.Column("premium", sa.Float(), nullable=True))
    op.add_column("strategy", sa.Column("funds", sa.Float(), nullable=True))
    op.add_column("strategy", sa.Column("min_quantity", sa.Float(), nullable=False))
    op.add_column("strategy", sa.Column("margin_for_min_quantity", sa.Float(), nullable=False))
    op.add_column("strategy", sa.Column("incremental_step_size", sa.Float(), nullable=False))
    op.add_column("strategy", sa.Column("compounding", sa.Boolean(), nullable=False))
    op.add_column("strategy", sa.Column("contracts", sa.Float(), nullable=True))
    op.add_column("strategy", sa.Column("funds_usage_percent", sa.Float(), nullable=False))
    op.drop_index("ix_trade_position", table_name="trade")
    op.drop_column("trade", "position")
    # Make Quantity and expiry nullable
    op.alter_column("trade", "quantity", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("trade", "expiry", existing_type=sa.DATE(), nullable=False)
    op.alter_column("trade", "entry_price", existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("trade", "expiry", existing_type=sa.DATE(), nullable=True)
    op.alter_column("trade", "quantity", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("trade", "entry_price", existing_type=sa.Float(), nullable=True)
    op.add_column(
        "trade", sa.Column("position", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_index("ix_trade_position", "trade", ["position"], unique=False)
    op.drop_column("strategy", "funds_usage_percent")
    op.drop_column("strategy", "contracts")
    op.drop_column("strategy", "compounding")
    op.drop_column("strategy", "incremental_step_size")
    op.drop_column("strategy", "margin_for_min_quantity")
    op.drop_column("strategy", "min_quantity")
    op.drop_column("strategy", "funds")
    op.drop_column("strategy", "premium")
    # ### end Alembic commands ###
