"""future_exit_price_received future_entry_price_received entry_price not nullable

Revision ID: 26c4f6ed6ca0
Revises: aa5951fdf5de
Create Date: 2024-01-29 14:40:20.849978

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "26c4f6ed6ca0"
down_revision = "aa5951fdf5de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trade", sa.Column("future_exit_price_received", sa.Float(), nullable=True))
    op.alter_column(
        "trade", "entry_price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "trade",
        "future_entry_price_received",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.create_index(op.f("ix_trade_action"), "trade", ["action"], unique=False)
    op.drop_column("trade", "future_exit_price")
    op.drop_column("trade", "future_entry_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade",
        sa.Column(
            "future_entry_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "trade",
        sa.Column(
            "future_exit_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_trade_action"), table_name="trade")
    op.alter_column(
        "trade",
        "future_entry_price_received",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "trade", "entry_price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.drop_column("trade", "future_exit_price_received")
    # ### end Alembic commands ###
